[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --production"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: https://*.facebook.com https://*.facebook.net https://*.fbcdn.net; style-src 'self' 'unsafe-inline' https: https://*.facebook.com; img-src 'self' data: https: https://*.facebook.com https://*.fbcdn.net https://*.facebook.net; font-src 'self' data: https:; connect-src 'self' https: https://*.facebook.com https://*.fbcdn.net; frame-src 'self' https: https://*.facebook.com https://*.facebook.net https://www.instagram.com; object-src 'none'"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Domain configuration
[context.production]
  # Your primary domain will be set in Netlify's dashboard
  publish = "dist"
  command = "npm run build"

[context.production.environment]
  VITE_APP_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    output_path = "reports/lighthouse.html"
    fail_deploy_on_score_thresholds = {performance = 0.7, accessibility = 0.8, "best-practices" = 0.8, seo = 0.8}
    audit_url = "/"
    thresholds = {performance = 0.7, accessibility = 0.8, "best-practices" = 0.8, seo = 0.8}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 